"""Medicine domain package.

Public surface of the Medicine bounded context. Only the names
re-exported here are considered stable for other layers (Application,
other domains) to import — internal module layout may be reorganised
freely without breaking callers.
"""
from .entities import Medicine, MedicineBatch
from .enums import (
    BarcodeType,
    BatchSource,
    BatchStatus,
    DosageForm,
    DrugSchedule,
    MedicineStatus,
    QuarantineReason,
    StockAdjustmentReason,
    StrengthUnit,
    UnitOfMeasure,
)
from .exceptions import (
    BarcodeNotFoundError,
    BatchExpiredError,
    BatchQuarantinedError,
    BatchRecalledError,
    DuplicateBarcodeError,
    InsufficientBatchQuantityError,
    InvalidBarcodeError,
    InvalidBatchNumberError,
    InvalidBatchQuantityError,
    InvalidCompositionError,
    InvalidExpiryDateError,
    InvalidGenericNameError,
    InvalidHSNCodeError,
    InvalidManufacturerReferenceError,
    InvalidManufacturingDateError,
    InvalidMedicineNameError,
    InvalidPackConfigurationError,
    InvalidStorageConditionError,
    MedicineAlreadyBannedError,
    MedicineAlreadyDiscontinuedError,
    MedicineDomainError,
    MedicineNotActiveError,
    TooManyAlternateNamesError,
    TooManyBarcodesError,
)
from .interfaces import MedicineBatchRepository, MedicineRepository
from .value_objects import (
    Barcode,
    BatchNumber,
    BatchQuantity,
    Composition,
    CompositionItem,
    ExpiryDate,
    GenericName,
    HSNCode,
    ManufacturerRef,
    ManufacturingDate,
    MedicineBatchId,
    MedicineId,
    MedicineName,
    PackConfiguration,
    ReceivedDate,
    StorageCondition,
)

__all__ = [
    "Medicine",
    "MedicineBatch",
    "MedicineId",
    "MedicineBatchId",
    "MedicineName",
    "GenericName",
    "Composition",
    "CompositionItem",
    "ManufacturerRef",
    "HSNCode",
    "PackConfiguration",
    "Barcode",
    "StorageCondition",
    "BatchNumber",
    "BatchQuantity",
    "ManufacturingDate",
    "ExpiryDate",
    "ReceivedDate",
    "DosageForm",
    "UnitOfMeasure",
    "StrengthUnit",
    "DrugSchedule",
    "MedicineStatus",
    "BarcodeType",
    "BatchStatus",
    "BatchSource",
    "QuarantineReason",
    "StockAdjustmentReason",
    "MedicineRepository",
    "MedicineBatchRepository",
    "MedicineDomainError",
    "InvalidMedicineNameError",
    "InvalidGenericNameError",
    "InvalidCompositionError",
    "InvalidHSNCodeError",
    "InvalidBarcodeError",
    "DuplicateBarcodeError",
    "BarcodeNotFoundError",
    "InvalidPackConfigurationError",
    "InvalidStorageConditionError",
    "InvalidManufacturerReferenceError",
    "MedicineAlreadyDiscontinuedError",
    "MedicineNotActiveError",
    "MedicineAlreadyBannedError",
    "TooManyBarcodesError",
    "TooManyAlternateNamesError",
    "InvalidBatchNumberError",
    "InvalidBatchQuantityError",
    "InvalidExpiryDateError",
    "InvalidManufacturingDateError",
    "BatchExpiredError",
    "BatchQuarantinedError",
    "BatchRecalledError",
    "InsufficientBatchQuantityError",
]
